name: CI/CD Pipeline - Docker Build & Test

# Trigger on push events to any branch
on:
  push:
    branches:
      - '**'  # all branches

jobs:
  build_and_test:
    name: Build Docker Image and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t gymtrainer:ci .

    - name: Run unit tests inside container
      run: |
        docker run --rm gymtrainer:ci pytest

